### ISSUE TITLE
"Unable to write into workspace configuration file because file is dirty"

### ISSUE THREAD

**Issue by a2sheppy** [vscode-glitch/vscode-glitch#13]
When I try to open a Glitch project after installing this extension, I get the error "Unable to write into workspace configuration file because the file is dirty. Please save it and try again." This is using the latest VS Code on macOS 10.15.

I try saving this and re-opening the project but no change. I've tried deleting the workspace and letting it get created anew. No change.

I wonder if the fact that the workspace name has a colon in it (which is not a legal character in file names on macOS for historical reasons) is the problem here. The colon is converted into a slash in the filename, which is strange since that's used as a path separator. Seems like a near guarantee things will get wonky fast. Maybe try changing it to use (glitch) or something instead of "Glitch:" to open the workspace name?

(If I rename the workspace file to "glitch--foo.code-workspace", the error no longer occurs but I get a workspace window with no files or folders in it).

**Comment by a2sheppy** [comment]
Diagnostic info:

```
generatedAt: 2019-10-28T21:16:56.672Z
sessionId: bb324e80-7691-4928-afc6-82fca1824ecf1572297372446
processUptime: 42
projectNames: []
platform:
  vscodeVersion: 1.39.2
  os: darwin
  osRelease: 19.0.0
  product: vscode
extensions:
  activeExtensions:
    alefragnani:
      Bookmarks: 10.5.0
    ban:
      spellright: 3.0.48
    dbaeumer:
      vscode-eslint: 1.9.1
    eamodio:
      gitlens: 10.1.1
    EditorConfig:
      EditorConfig: 0.14.2
    GitHub:
      vscode-pull-request-github: 0.12.0
    glitch:
      glitch: 0.1.3
    golf1052:
      base16-generator: 1.9.0
    joelday:
      docthis: 0.7.1
    pranaygp:
      vscode-css-peek: 3.0.2
    vscode-icons-team:
      vscode-icons: 9.5.0
  inactiveExtensions:
    ms-vscode:
      node-debug: 1.38.8
      node-debug2: 1.39.1
      references-view: 0.0.30
      cpptools: 0.26.1
    Agenric:
      cocoapods-snippets: 1.0.0
    anseki:
      vscode-color: 0.4.5
    christian-kohler:
      npm-intellisense: 1.3.0
    dave-deletethis:
      midl-webidl-syntax: 0.0.1
    emmanuelbeziat:
      vscode-great-icons: 2.1.47
    eriklynd:
      json-tools: 1.0.2
    Flixs:
      vs-code-http-server-and-html-preview: 2.2.2
    fmoronzirfas:
      open-in-marked: 1.0.8
    henoc:
      svgeditor: 2.9.0
    ionicabizau:
      ms-dos-editor-theme: 1.0.5
    ms-python:
      python: 2019.10.44104
    mushan:
      vscode-open-iterm2: 0.0.4
    nickdemayo:
      vscode-json-editor: 0.2.3
    peakchen90:
      open-html-in-browser: 2.1.0
    richie5um2:
      vscode-sort-json: 1.17.0
    Septh:
      wow-bundle: 1.3.0
    taniarascia:
      new-moon-vscode: 1.8.8
memStats:
  freemem: 279.67
  totalmem: 49152
  rss: 207.59
  heapTotal: 112.03
  heapUsed: 104.05
  external: 0.11
```
