### ISSUE TITLE
Corruption of code when editing using the VS Code extension

### ISSUE THREAD

**Issue by ubershmekel** [vscode-glitch/vscode-glitch#24]
I've had this corruption of data happen on multiple different projects and in varying levels of terrible. At this point I'd recommend nobody use the VS Code extension. I've left a review as such at https://marketplace.visualstudio.com/items?itemName=glitch.glitch&ssr=false#review-details

What happened to me exactly this time that I got tired of the files being broken by the extension:

* https://glitch.com/edit/#!/draw-conf-2?path=src%2Fcomponents%2FCall%2FCall.js%3A18%3A38
* I was editing this file in VS Code, added a few lines, made some lines a comment
* Almost all of the files were deleted from the project on Glitch.com and I had to rewind to recover them.

**Comment by dluxemburg** [comment]
Hi @ubershmekel, sorry you're running into this.

We've seen similar issues when the Glitch extension is being used along with certain other extensions that update the file state, they sort of step on each other in weird ways some times.

Can you tell me what other extensions you are running and what OS you're on? There's a "Glitch: Show Diagnostic Information" command that will generate output you can copy-and-paste.

**Comment by ubershmekel** [comment]
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Type	x64-based PC

generatedAt: 2020-05-26T16:13:05.526Z
sessionId: 5e5f9f92-1b61-4f7b-ae45-4bf3dec01f0e1590509576694
processUptime: 8
projectNames:
  - draw-conf-2
platform:
  vscodeVersion: 1.45.1
  os: win32
  osRelease: 10.0.18363
  product: vscode
extensions:
  activeExtensions:
    dbaeumer:
      vscode-eslint: 2.1.5
    donjayamanne:
      githistory: 0.6.5
    eg2:
      vscode-npm-script: 0.3.11
    glitch:
      glitch: 0.1.6
    GrapeCity:
      gc-excelviewer: 2.1.34
    mechatroner:
      rainbow-csv: 1.7.0
    slevesque:
      vscode-hexdump: 1.7.2
  inactiveExtensions:
    ms-vscode:
      js-debug-companion: 1.0.0
      node-debug: 1.44.5
      node-debug2: 1.42.2
      references-view: 0.0.51
      cpptools: 0.28.1
      vscode-typescript-tslint-plugin: 1.2.3
    cstrachan:
      vcard: 1.0.1
    eg2:
      tslint: 1.0.44
    ms-azuretools:
      vscode-docker: 1.2.0
    ms-python:
      python: 2020.5.80290
    octref:
      vetur: 0.24.0
memStats:
  freemem: 17527.28
  totalmem: 32706.66
  rss: 163.48
  heapTotal: 117.25
  heapUsed: 89.68
  external: 7.76
```
