### ISSUE TITLE
Glitch fails to sign in on Code OSS with Internal Server Error

### ISSUE THREAD

**Issue by wolfiediscord** [vscode-glitch/vscode-glitch#25]
When attempting to sign into Glitch using Code OSS, it fails with Internal Server Error.
Signing in using the glitch.com option, gives an error stating that it is not a valid URL.
Using the email code option allows you to input an email code, but upon entering the code, it fails with Internal Server Error. I have tried disabling ufw, but it did not effect anything. The glitch status page does not show anything that would effect this.

Specifications:
![image](https://user-images.githubusercontent.com/45970663/84472873-ae99dd80-ac4d-11ea-8c28-cd270197eb3c.png)

Invalid URL: 
https://glitch.com/vscode-auth?scheme=code-oss

Output of Glitch: Show Diagnostic Information
```
generatedAt: 2020-06-12T06:42:53.465Z
sessionId: someValue.sessionId
processUptime: 326
projectNames: []
platform:
  vscodeVersion: 1.46.0
  os: linux
  osRelease: 5.7.2-arch1-1
  product: code-oss
extensions:
  activeExtensions:
    glitch:
      glitch: 0.1.6
  inactiveExtensions:
    ms-vscode:
      js-debug: 1.46.1
      js-debug-companion: 1.0.2
      node-debug: 1.44.6
      node-debug2: 1.42.4
      references-view: 0.0.57
      vscode-js-profile-table: 0.0.5
memStats:
  freemem: 2981
  totalmem: 7690.12
  rss: 171.7
  heapTotal: 50.91
  heapUsed: 49.13
  external: 1.51
```
